import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(await readFile(resolve(root, 'source-manifest.json'), 'utf8'));
const parts = await Promise.all(manifest.files.map(async ({ path }) =>
  readFile(resolve(root, path), 'utf8')
));
const source = parts.join('');
const storageAdapter = await readFile(resolve(root, 'src/adapters/storage.js'), 'utf8');
const logMathModule = await readFile(resolve(root, 'src/modules/log-math.js'), 'utf8');
const saveCodecModule = await readFile(resolve(root, 'src/modules/save-codec.js'), 'utf8');
const actualHash = createHash('sha256').update(source).digest('hex');
if (actualHash !== (manifest.candidateSourceSha256 ?? manifest.baselineSha256)) {
  throw new Error('Candidate source changed. Review the source diff and update the manifest deliberately before building.');
}
const inputHash = createHash('sha256')
  .update([source, storageAdapter, logMathModule, saveCodecModule].join('\0'))
  .digest('hex');
if (inputHash !== manifest.candidateInputsSha256) {
  throw new Error('A candidate adapter or module changed. Review the change and update the manifest deliberately before building.');
}

const prelude = `/* Wave Incremental help candidate: baseline ${manifest.baselineCommit}.
 * Generated from Issue/help/src by Issue/help/build.mjs. Do not edit this file.
 * Gameplay code follows the fixed baseline except for reviewed pure modules.
 */
(function waveHelpPreview() {
  // All candidate save keys are isolated from the production game, including
  // manual slots, slot names, and the last selected tab.
  const HELP_STORAGE_PREFIX = 'waveIncremental_help_';
${storageAdapter}
${logMathModule}
${saveCodecModule}
  const localStorage = createScopedStorage(globalThis, HELP_STORAGE_PREFIX);
  const { encodeSave, decodeSave } = createSaveCodec(globalThis);

`;

const appendix = `
  // Preview-only inspection surface. It is intentionally absent from the
  // production game and does not expose arbitrary eval.
  const debugCalls = Object.freeze({
    clampLog, logAddLogs, logAddSigned, cmpGE, cmpLT,
    FLog, F, temperatureLog, up1CostLogAt, up2CostLogAt,
    buyUp1, buyUp2, buyUp3, buyPG1, buyPG2, buyPG3,
    bulkBuyUp1, bulkBuyUp2, bulkBuyPG1, bulkBuyPG2, bulkBuyPG3,
    applyProduction, runAutomation, runOfflineSimulation, tick,
    saveGame, loadGame, renderAll,
  });
  Object.defineProperty(globalThis, '__waveHelpDebug', {
    configurable: true,
    value: Object.freeze({
      baselineCommit: '${manifest.baselineCommit}',
      storagePrefix: HELP_STORAGE_PREFIX,
      snapshot: () => structuredClone(state),
      load(snapshot) {
        state = structuredClone(snapshot);
        dirty = true;
        renderAll();
      },
      call(name, ...args) {
        if (!Object.prototype.hasOwnProperty.call(debugCalls, name)) {
          throw new Error('Unknown debug call: ' + name);
        }
        return debugCalls[name](...args);
      },
    }),
  });
})();
`;

await writeFile(resolve(root, 'game.js'), prelude + source + appendix, 'utf8');
console.log(`Built Issue/help/game.js from ${manifest.files.length} source sections`);
